###
GET http://localhost:8008/api/v1/order/
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmZWF0dXJlcyI6WyJCVVRUT05fREVMRVRFX09SREVSIiwiUEFHRV9PUkRFUl9NQU5BR0VNRU5UIl0sInN1YiI6IjIiLCJpc3MiOiJQaXJhdGVCYXkiLCJ0eXBlIjoiQVVUSE4iLCJleHAiOjE1OTMxNDc0MTh9.uaQXVRPDuKoYZLqvcHhC8hUlywrG4et4EsqQmAWBiOM
Accept: application/json


###
GET http://localhost:8008/api/v1/order/2
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmZWF0dXJlcyI6WyJCVVRUT05fREVMRVRFX09SREVSIiwiUEFHRV9PUkRFUl9NQU5BR0VNRU5UIl0sInN1YiI6IjIiLCJpc3MiOiJQaXJhdGVCYXkiLCJ0eXBlIjoiQVVUSE4iLCJleHAiOjE1OTMxNDc0MTh9.uaQXVRPDuKoYZLqvcHhC8hUlywrG4et4EsqQmAWBiOM
Accept: application/json


###
GET http://localhost:8008/api/v1/order/2/products
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmZWF0dXJlcyI6WyJCVVRUT05fREVMRVRFX09SREVSIiwiUEFHRV9PUkRFUl9NQU5BR0VNRU5UIl0sInN1YiI6IjIiLCJpc3MiOiJQaXJhdGVCYXkiLCJ0eXBlIjoiQVVUSE4iLCJleHAiOjE1OTMxNDc0MTh9.uaQXVRPDuKoYZLqvcHhC8hUlywrG4et4EsqQmAWBiOM
Accept: application/json